/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@verdocs/web-sdk';

import { defineCustomElements } from '@verdocs/web-sdk/loader';

defineCustomElements();
export const IpcTest = /*@__PURE__*/createReactComponent<JSX.IpcTest, HTMLIpcTestElement>('ipc-test');
export const VerdocsActivityBox = /*@__PURE__*/createReactComponent<JSX.VerdocsActivityBox, HTMLVerdocsActivityBoxElement>('verdocs-activity-box');
export const VerdocsAuth = /*@__PURE__*/createReactComponent<JSX.VerdocsAuth, HTMLVerdocsAuthElement>('verdocs-auth');
export const VerdocsBuild = /*@__PURE__*/createReactComponent<JSX.VerdocsBuild, HTMLVerdocsBuildElement>('verdocs-build');
export const VerdocsButton = /*@__PURE__*/createReactComponent<JSX.VerdocsButton, HTMLVerdocsButtonElement>('verdocs-button');
export const VerdocsButtonPanel = /*@__PURE__*/createReactComponent<JSX.VerdocsButtonPanel, HTMLVerdocsButtonPanelElement>('verdocs-button-panel');
export const VerdocsCheckbox = /*@__PURE__*/createReactComponent<JSX.VerdocsCheckbox, HTMLVerdocsCheckboxElement>('verdocs-checkbox');
export const VerdocsComponentError = /*@__PURE__*/createReactComponent<JSX.VerdocsComponentError, HTMLVerdocsComponentErrorElement>('verdocs-component-error');
export const VerdocsContactPicker = /*@__PURE__*/createReactComponent<JSX.VerdocsContactPicker, HTMLVerdocsContactPickerElement>('verdocs-contact-picker');
export const VerdocsDropdown = /*@__PURE__*/createReactComponent<JSX.VerdocsDropdown, HTMLVerdocsDropdownElement>('verdocs-dropdown');
export const VerdocsEnvelopeDocumentPage = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeDocumentPage, HTMLVerdocsEnvelopeDocumentPageElement>('verdocs-envelope-document-page');
export const VerdocsEnvelopeRecipientLink = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeRecipientLink, HTMLVerdocsEnvelopeRecipientLinkElement>('verdocs-envelope-recipient-link');
export const VerdocsEnvelopeRecipientSummary = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeRecipientSummary, HTMLVerdocsEnvelopeRecipientSummaryElement>('verdocs-envelope-recipient-summary');
export const VerdocsEnvelopeSidebar = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeSidebar, HTMLVerdocsEnvelopeSidebarElement>('verdocs-envelope-sidebar');
export const VerdocsEnvelopesList = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopesList, HTMLVerdocsEnvelopesListElement>('verdocs-envelopes-list');
export const VerdocsFieldAttachment = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldAttachment, HTMLVerdocsFieldAttachmentElement>('verdocs-field-attachment');
export const VerdocsFieldCheckbox = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldCheckbox, HTMLVerdocsFieldCheckboxElement>('verdocs-field-checkbox');
export const VerdocsFieldDate = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldDate, HTMLVerdocsFieldDateElement>('verdocs-field-date');
export const VerdocsFieldDropdown = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldDropdown, HTMLVerdocsFieldDropdownElement>('verdocs-field-dropdown');
export const VerdocsFieldInitial = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldInitial, HTMLVerdocsFieldInitialElement>('verdocs-field-initial');
export const VerdocsFieldPayment = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldPayment, HTMLVerdocsFieldPaymentElement>('verdocs-field-payment');
export const VerdocsFieldRadioButton = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldRadioButton, HTMLVerdocsFieldRadioButtonElement>('verdocs-field-radio-button');
export const VerdocsFieldSignature = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldSignature, HTMLVerdocsFieldSignatureElement>('verdocs-field-signature');
export const VerdocsFieldTextarea = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldTextarea, HTMLVerdocsFieldTextareaElement>('verdocs-field-textarea');
export const VerdocsFieldTextbox = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldTextbox, HTMLVerdocsFieldTextboxElement>('verdocs-field-textbox');
export const VerdocsFieldTimestamp = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldTimestamp, HTMLVerdocsFieldTimestampElement>('verdocs-field-timestamp');
export const VerdocsFileChooser = /*@__PURE__*/createReactComponent<JSX.VerdocsFileChooser, HTMLVerdocsFileChooserElement>('verdocs-file-chooser');
export const VerdocsFloatingMenu = /*@__PURE__*/createReactComponent<JSX.VerdocsFloatingMenu, HTMLVerdocsFloatingMenuElement>('verdocs-floating-menu');
export const VerdocsHelpIcon = /*@__PURE__*/createReactComponent<JSX.VerdocsHelpIcon, HTMLVerdocsHelpIconElement>('verdocs-help-icon');
export const VerdocsInitialDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsInitialDialog, HTMLVerdocsInitialDialogElement>('verdocs-initial-dialog');
export const VerdocsKbaDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsKbaDialog, HTMLVerdocsKbaDialogElement>('verdocs-kba-dialog');
export const VerdocsLoader = /*@__PURE__*/createReactComponent<JSX.VerdocsLoader, HTMLVerdocsLoaderElement>('verdocs-loader');
export const VerdocsOkDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsOkDialog, HTMLVerdocsOkDialogElement>('verdocs-ok-dialog');
export const VerdocsOrganizationCard = /*@__PURE__*/createReactComponent<JSX.VerdocsOrganizationCard, HTMLVerdocsOrganizationCardElement>('verdocs-organization-card');
export const VerdocsPagination = /*@__PURE__*/createReactComponent<JSX.VerdocsPagination, HTMLVerdocsPaginationElement>('verdocs-pagination');
export const VerdocsPreview = /*@__PURE__*/createReactComponent<JSX.VerdocsPreview, HTMLVerdocsPreviewElement>('verdocs-preview');
export const VerdocsProgressBar = /*@__PURE__*/createReactComponent<JSX.VerdocsProgressBar, HTMLVerdocsProgressBarElement>('verdocs-progress-bar');
export const VerdocsQuickFilter = /*@__PURE__*/createReactComponent<JSX.VerdocsQuickFilter, HTMLVerdocsQuickFilterElement>('verdocs-quick-filter');
export const VerdocsQuickFunctions = /*@__PURE__*/createReactComponent<JSX.VerdocsQuickFunctions, HTMLVerdocsQuickFunctionsElement>('verdocs-quick-functions');
export const VerdocsRadioButton = /*@__PURE__*/createReactComponent<JSX.VerdocsRadioButton, HTMLVerdocsRadioButtonElement>('verdocs-radio-button');
export const VerdocsSearch = /*@__PURE__*/createReactComponent<JSX.VerdocsSearch, HTMLVerdocsSearchElement>('verdocs-search');
export const VerdocsSearchActivity = /*@__PURE__*/createReactComponent<JSX.VerdocsSearchActivity, HTMLVerdocsSearchActivityElement>('verdocs-search-activity');
export const VerdocsSearchBox = /*@__PURE__*/createReactComponent<JSX.VerdocsSearchBox, HTMLVerdocsSearchBoxElement>('verdocs-search-box');
export const VerdocsSearchTabs = /*@__PURE__*/createReactComponent<JSX.VerdocsSearchTabs, HTMLVerdocsSearchTabsElement>('verdocs-search-tabs');
export const VerdocsSelectInput = /*@__PURE__*/createReactComponent<JSX.VerdocsSelectInput, HTMLVerdocsSelectInputElement>('verdocs-select-input');
export const VerdocsSend = /*@__PURE__*/createReactComponent<JSX.VerdocsSend, HTMLVerdocsSendElement>('verdocs-send');
export const VerdocsSign = /*@__PURE__*/createReactComponent<JSX.VerdocsSign, HTMLVerdocsSignElement>('verdocs-sign');
export const VerdocsSignatureDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsSignatureDialog, HTMLVerdocsSignatureDialogElement>('verdocs-signature-dialog');
export const VerdocsSpinner = /*@__PURE__*/createReactComponent<JSX.VerdocsSpinner, HTMLVerdocsSpinnerElement>('verdocs-spinner');
export const VerdocsStatusIndicator = /*@__PURE__*/createReactComponent<JSX.VerdocsStatusIndicator, HTMLVerdocsStatusIndicatorElement>('verdocs-status-indicator');
export const VerdocsTemplateAttachments = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateAttachments, HTMLVerdocsTemplateAttachmentsElement>('verdocs-template-attachments');
export const VerdocsTemplateCard = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateCard, HTMLVerdocsTemplateCardElement>('verdocs-template-card');
export const VerdocsTemplateCreate = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateCreate, HTMLVerdocsTemplateCreateElement>('verdocs-template-create');
export const VerdocsTemplateDocumentPage = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateDocumentPage, HTMLVerdocsTemplateDocumentPageElement>('verdocs-template-document-page');
export const VerdocsTemplateFieldProperties = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateFieldProperties, HTMLVerdocsTemplateFieldPropertiesElement>('verdocs-template-field-properties');
export const VerdocsTemplateFields = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateFields, HTMLVerdocsTemplateFieldsElement>('verdocs-template-fields');
export const VerdocsTemplateName = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateName, HTMLVerdocsTemplateNameElement>('verdocs-template-name');
export const VerdocsTemplateReminders = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateReminders, HTMLVerdocsTemplateRemindersElement>('verdocs-template-reminders');
export const VerdocsTemplateRoleProperties = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateRoleProperties, HTMLVerdocsTemplateRolePropertiesElement>('verdocs-template-role-properties');
export const VerdocsTemplateRoles = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateRoles, HTMLVerdocsTemplateRolesElement>('verdocs-template-roles');
export const VerdocsTemplateSender = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateSender, HTMLVerdocsTemplateSenderElement>('verdocs-template-sender');
export const VerdocsTemplateStar = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateStar, HTMLVerdocsTemplateStarElement>('verdocs-template-star');
export const VerdocsTemplateTags = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateTags, HTMLVerdocsTemplateTagsElement>('verdocs-template-tags');
export const VerdocsTemplateVisibility = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateVisibility, HTMLVerdocsTemplateVisibilityElement>('verdocs-template-visibility');
export const VerdocsTemplatesList = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplatesList, HTMLVerdocsTemplatesListElement>('verdocs-templates-list');
export const VerdocsTextInput = /*@__PURE__*/createReactComponent<JSX.VerdocsTextInput, HTMLVerdocsTextInputElement>('verdocs-text-input');
export const VerdocsToggle = /*@__PURE__*/createReactComponent<JSX.VerdocsToggle, HTMLVerdocsToggleElement>('verdocs-toggle');
export const VerdocsToggleButton = /*@__PURE__*/createReactComponent<JSX.VerdocsToggleButton, HTMLVerdocsToggleButtonElement>('verdocs-toggle-button');
export const VerdocsToolbarIcon = /*@__PURE__*/createReactComponent<JSX.VerdocsToolbarIcon, HTMLVerdocsToolbarIconElement>('verdocs-toolbar-icon');
export const VerdocsUploadDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsUploadDialog, HTMLVerdocsUploadDialogElement>('verdocs-upload-dialog');
export const VerdocsView = /*@__PURE__*/createReactComponent<JSX.VerdocsView, HTMLVerdocsViewElement>('verdocs-view');
