/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@verdocs/web-sdk/dist/types';

import { defineCustomElement as defineVerdocsActivityBox } from '@verdocs/web-sdk/dist/components/verdocs-activity-box.js';
import { defineCustomElement as defineVerdocsAuth } from '@verdocs/web-sdk/dist/components/verdocs-auth.js';
import { defineCustomElement as defineVerdocsBuild } from '@verdocs/web-sdk/dist/components/verdocs-build.js';
import { defineCustomElement as defineVerdocsButton } from '@verdocs/web-sdk/dist/components/verdocs-button.js';
import { defineCustomElement as defineVerdocsButtonPanel } from '@verdocs/web-sdk/dist/components/verdocs-button-panel.js';
import { defineCustomElement as defineVerdocsCheckbox } from '@verdocs/web-sdk/dist/components/verdocs-checkbox.js';
import { defineCustomElement as defineVerdocsComponentError } from '@verdocs/web-sdk/dist/components/verdocs-component-error.js';
import { defineCustomElement as defineVerdocsContactPicker } from '@verdocs/web-sdk/dist/components/verdocs-contact-picker.js';
import { defineCustomElement as defineVerdocsDialog } from '@verdocs/web-sdk/dist/components/verdocs-dialog.js';
import { defineCustomElement as defineVerdocsDropdown } from '@verdocs/web-sdk/dist/components/verdocs-dropdown.js';
import { defineCustomElement as defineVerdocsEnvelopeDocumentPage } from '@verdocs/web-sdk/dist/components/verdocs-envelope-document-page.js';
import { defineCustomElement as defineVerdocsEnvelopeRecipientLink } from '@verdocs/web-sdk/dist/components/verdocs-envelope-recipient-link.js';
import { defineCustomElement as defineVerdocsEnvelopeRecipientSummary } from '@verdocs/web-sdk/dist/components/verdocs-envelope-recipient-summary.js';
import { defineCustomElement as defineVerdocsEnvelopeSidebar } from '@verdocs/web-sdk/dist/components/verdocs-envelope-sidebar.js';
import { defineCustomElement as defineVerdocsEnvelopesList } from '@verdocs/web-sdk/dist/components/verdocs-envelopes-list.js';
import { defineCustomElement as defineVerdocsFieldAttachment } from '@verdocs/web-sdk/dist/components/verdocs-field-attachment.js';
import { defineCustomElement as defineVerdocsFieldCheckbox } from '@verdocs/web-sdk/dist/components/verdocs-field-checkbox.js';
import { defineCustomElement as defineVerdocsFieldDate } from '@verdocs/web-sdk/dist/components/verdocs-field-date.js';
import { defineCustomElement as defineVerdocsFieldDropdown } from '@verdocs/web-sdk/dist/components/verdocs-field-dropdown.js';
import { defineCustomElement as defineVerdocsFieldInitial } from '@verdocs/web-sdk/dist/components/verdocs-field-initial.js';
import { defineCustomElement as defineVerdocsFieldPayment } from '@verdocs/web-sdk/dist/components/verdocs-field-payment.js';
import { defineCustomElement as defineVerdocsFieldRadioButton } from '@verdocs/web-sdk/dist/components/verdocs-field-radio-button.js';
import { defineCustomElement as defineVerdocsFieldSignature } from '@verdocs/web-sdk/dist/components/verdocs-field-signature.js';
import { defineCustomElement as defineVerdocsFieldTextarea } from '@verdocs/web-sdk/dist/components/verdocs-field-textarea.js';
import { defineCustomElement as defineVerdocsFieldTextbox } from '@verdocs/web-sdk/dist/components/verdocs-field-textbox.js';
import { defineCustomElement as defineVerdocsFieldTimestamp } from '@verdocs/web-sdk/dist/components/verdocs-field-timestamp.js';
import { defineCustomElement as defineVerdocsFileChooser } from '@verdocs/web-sdk/dist/components/verdocs-file-chooser.js';
import { defineCustomElement as defineVerdocsHelpIcon } from '@verdocs/web-sdk/dist/components/verdocs-help-icon.js';
import { defineCustomElement as defineVerdocsInitialDialog } from '@verdocs/web-sdk/dist/components/verdocs-initial-dialog.js';
import { defineCustomElement as defineVerdocsKbaDialog } from '@verdocs/web-sdk/dist/components/verdocs-kba-dialog.js';
import { defineCustomElement as defineVerdocsLoader } from '@verdocs/web-sdk/dist/components/verdocs-loader.js';
import { defineCustomElement as defineVerdocsOkDialog } from '@verdocs/web-sdk/dist/components/verdocs-ok-dialog.js';
import { defineCustomElement as defineVerdocsOrganizationCard } from '@verdocs/web-sdk/dist/components/verdocs-organization-card.js';
import { defineCustomElement as defineVerdocsPagination } from '@verdocs/web-sdk/dist/components/verdocs-pagination.js';
import { defineCustomElement as defineVerdocsPortal } from '@verdocs/web-sdk/dist/components/verdocs-portal.js';
import { defineCustomElement as defineVerdocsPreview } from '@verdocs/web-sdk/dist/components/verdocs-preview.js';
import { defineCustomElement as defineVerdocsProgressBar } from '@verdocs/web-sdk/dist/components/verdocs-progress-bar.js';
import { defineCustomElement as defineVerdocsQuickFilter } from '@verdocs/web-sdk/dist/components/verdocs-quick-filter.js';
import { defineCustomElement as defineVerdocsQuickFunctions } from '@verdocs/web-sdk/dist/components/verdocs-quick-functions.js';
import { defineCustomElement as defineVerdocsRadioButton } from '@verdocs/web-sdk/dist/components/verdocs-radio-button.js';
import { defineCustomElement as defineVerdocsSearch } from '@verdocs/web-sdk/dist/components/verdocs-search.js';
import { defineCustomElement as defineVerdocsSearchBox } from '@verdocs/web-sdk/dist/components/verdocs-search-box.js';
import { defineCustomElement as defineVerdocsSearchTabs } from '@verdocs/web-sdk/dist/components/verdocs-search-tabs.js';
import { defineCustomElement as defineVerdocsSelectInput } from '@verdocs/web-sdk/dist/components/verdocs-select-input.js';
import { defineCustomElement as defineVerdocsSend } from '@verdocs/web-sdk/dist/components/verdocs-send.js';
import { defineCustomElement as defineVerdocsSign } from '@verdocs/web-sdk/dist/components/verdocs-sign.js';
import { defineCustomElement as defineVerdocsSignatureDialog } from '@verdocs/web-sdk/dist/components/verdocs-signature-dialog.js';
import { defineCustomElement as defineVerdocsSpinner } from '@verdocs/web-sdk/dist/components/verdocs-spinner.js';
import { defineCustomElement as defineVerdocsStatusIndicator } from '@verdocs/web-sdk/dist/components/verdocs-status-indicator.js';
import { defineCustomElement as defineVerdocsTable } from '@verdocs/web-sdk/dist/components/verdocs-table.js';
import { defineCustomElement as defineVerdocsTabs } from '@verdocs/web-sdk/dist/components/verdocs-tabs.js';
import { defineCustomElement as defineVerdocsTemplateAttachments } from '@verdocs/web-sdk/dist/components/verdocs-template-attachments.js';
import { defineCustomElement as defineVerdocsTemplateBuildTabs } from '@verdocs/web-sdk/dist/components/verdocs-template-build-tabs.js';
import { defineCustomElement as defineVerdocsTemplateCard } from '@verdocs/web-sdk/dist/components/verdocs-template-card.js';
import { defineCustomElement as defineVerdocsTemplateCreate } from '@verdocs/web-sdk/dist/components/verdocs-template-create.js';
import { defineCustomElement as defineVerdocsTemplateDocumentPage } from '@verdocs/web-sdk/dist/components/verdocs-template-document-page.js';
import { defineCustomElement as defineVerdocsTemplateFieldProperties } from '@verdocs/web-sdk/dist/components/verdocs-template-field-properties.js';
import { defineCustomElement as defineVerdocsTemplateFields } from '@verdocs/web-sdk/dist/components/verdocs-template-fields.js';
import { defineCustomElement as defineVerdocsTemplateName } from '@verdocs/web-sdk/dist/components/verdocs-template-name.js';
import { defineCustomElement as defineVerdocsTemplateReminders } from '@verdocs/web-sdk/dist/components/verdocs-template-reminders.js';
import { defineCustomElement as defineVerdocsTemplateRoleProperties } from '@verdocs/web-sdk/dist/components/verdocs-template-role-properties.js';
import { defineCustomElement as defineVerdocsTemplateRoles } from '@verdocs/web-sdk/dist/components/verdocs-template-roles.js';
import { defineCustomElement as defineVerdocsTemplateSender } from '@verdocs/web-sdk/dist/components/verdocs-template-sender.js';
import { defineCustomElement as defineVerdocsTemplateStar } from '@verdocs/web-sdk/dist/components/verdocs-template-star.js';
import { defineCustomElement as defineVerdocsTemplateTags } from '@verdocs/web-sdk/dist/components/verdocs-template-tags.js';
import { defineCustomElement as defineVerdocsTemplateVisibility } from '@verdocs/web-sdk/dist/components/verdocs-template-visibility.js';
import { defineCustomElement as defineVerdocsTemplatesList } from '@verdocs/web-sdk/dist/components/verdocs-templates-list.js';
import { defineCustomElement as defineVerdocsTextInput } from '@verdocs/web-sdk/dist/components/verdocs-text-input.js';
import { defineCustomElement as defineVerdocsToggle } from '@verdocs/web-sdk/dist/components/verdocs-toggle.js';
import { defineCustomElement as defineVerdocsToggleButton } from '@verdocs/web-sdk/dist/components/verdocs-toggle-button.js';
import { defineCustomElement as defineVerdocsToolbarIcon } from '@verdocs/web-sdk/dist/components/verdocs-toolbar-icon.js';
import { defineCustomElement as defineVerdocsUploadDialog } from '@verdocs/web-sdk/dist/components/verdocs-upload-dialog.js';
import { defineCustomElement as defineVerdocsView } from '@verdocs/web-sdk/dist/components/verdocs-view.js';

export const VerdocsActivityBox = /*@__PURE__*/createReactComponent<JSX.VerdocsActivityBox, HTMLVerdocsActivityBoxElement>('verdocs-activity-box', undefined, undefined, defineVerdocsActivityBox);
export const VerdocsAuth = /*@__PURE__*/createReactComponent<JSX.VerdocsAuth, HTMLVerdocsAuthElement>('verdocs-auth', undefined, undefined, defineVerdocsAuth);
export const VerdocsBuild = /*@__PURE__*/createReactComponent<JSX.VerdocsBuild, HTMLVerdocsBuildElement>('verdocs-build', undefined, undefined, defineVerdocsBuild);
export const VerdocsButton = /*@__PURE__*/createReactComponent<JSX.VerdocsButton, HTMLVerdocsButtonElement>('verdocs-button', undefined, undefined, defineVerdocsButton);
export const VerdocsButtonPanel = /*@__PURE__*/createReactComponent<JSX.VerdocsButtonPanel, HTMLVerdocsButtonPanelElement>('verdocs-button-panel', undefined, undefined, defineVerdocsButtonPanel);
export const VerdocsCheckbox = /*@__PURE__*/createReactComponent<JSX.VerdocsCheckbox, HTMLVerdocsCheckboxElement>('verdocs-checkbox', undefined, undefined, defineVerdocsCheckbox);
export const VerdocsComponentError = /*@__PURE__*/createReactComponent<JSX.VerdocsComponentError, HTMLVerdocsComponentErrorElement>('verdocs-component-error', undefined, undefined, defineVerdocsComponentError);
export const VerdocsContactPicker = /*@__PURE__*/createReactComponent<JSX.VerdocsContactPicker, HTMLVerdocsContactPickerElement>('verdocs-contact-picker', undefined, undefined, defineVerdocsContactPicker);
export const VerdocsDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsDialog, HTMLVerdocsDialogElement>('verdocs-dialog', undefined, undefined, defineVerdocsDialog);
export const VerdocsDropdown = /*@__PURE__*/createReactComponent<JSX.VerdocsDropdown, HTMLVerdocsDropdownElement>('verdocs-dropdown', undefined, undefined, defineVerdocsDropdown);
export const VerdocsEnvelopeDocumentPage = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeDocumentPage, HTMLVerdocsEnvelopeDocumentPageElement>('verdocs-envelope-document-page', undefined, undefined, defineVerdocsEnvelopeDocumentPage);
export const VerdocsEnvelopeRecipientLink = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeRecipientLink, HTMLVerdocsEnvelopeRecipientLinkElement>('verdocs-envelope-recipient-link', undefined, undefined, defineVerdocsEnvelopeRecipientLink);
export const VerdocsEnvelopeRecipientSummary = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeRecipientSummary, HTMLVerdocsEnvelopeRecipientSummaryElement>('verdocs-envelope-recipient-summary', undefined, undefined, defineVerdocsEnvelopeRecipientSummary);
export const VerdocsEnvelopeSidebar = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopeSidebar, HTMLVerdocsEnvelopeSidebarElement>('verdocs-envelope-sidebar', undefined, undefined, defineVerdocsEnvelopeSidebar);
export const VerdocsEnvelopesList = /*@__PURE__*/createReactComponent<JSX.VerdocsEnvelopesList, HTMLVerdocsEnvelopesListElement>('verdocs-envelopes-list', undefined, undefined, defineVerdocsEnvelopesList);
export const VerdocsFieldAttachment = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldAttachment, HTMLVerdocsFieldAttachmentElement>('verdocs-field-attachment', undefined, undefined, defineVerdocsFieldAttachment);
export const VerdocsFieldCheckbox = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldCheckbox, HTMLVerdocsFieldCheckboxElement>('verdocs-field-checkbox', undefined, undefined, defineVerdocsFieldCheckbox);
export const VerdocsFieldDate = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldDate, HTMLVerdocsFieldDateElement>('verdocs-field-date', undefined, undefined, defineVerdocsFieldDate);
export const VerdocsFieldDropdown = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldDropdown, HTMLVerdocsFieldDropdownElement>('verdocs-field-dropdown', undefined, undefined, defineVerdocsFieldDropdown);
export const VerdocsFieldInitial = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldInitial, HTMLVerdocsFieldInitialElement>('verdocs-field-initial', undefined, undefined, defineVerdocsFieldInitial);
export const VerdocsFieldPayment = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldPayment, HTMLVerdocsFieldPaymentElement>('verdocs-field-payment', undefined, undefined, defineVerdocsFieldPayment);
export const VerdocsFieldRadioButton = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldRadioButton, HTMLVerdocsFieldRadioButtonElement>('verdocs-field-radio-button', undefined, undefined, defineVerdocsFieldRadioButton);
export const VerdocsFieldSignature = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldSignature, HTMLVerdocsFieldSignatureElement>('verdocs-field-signature', undefined, undefined, defineVerdocsFieldSignature);
export const VerdocsFieldTextarea = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldTextarea, HTMLVerdocsFieldTextareaElement>('verdocs-field-textarea', undefined, undefined, defineVerdocsFieldTextarea);
export const VerdocsFieldTextbox = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldTextbox, HTMLVerdocsFieldTextboxElement>('verdocs-field-textbox', undefined, undefined, defineVerdocsFieldTextbox);
export const VerdocsFieldTimestamp = /*@__PURE__*/createReactComponent<JSX.VerdocsFieldTimestamp, HTMLVerdocsFieldTimestampElement>('verdocs-field-timestamp', undefined, undefined, defineVerdocsFieldTimestamp);
export const VerdocsFileChooser = /*@__PURE__*/createReactComponent<JSX.VerdocsFileChooser, HTMLVerdocsFileChooserElement>('verdocs-file-chooser', undefined, undefined, defineVerdocsFileChooser);
export const VerdocsHelpIcon = /*@__PURE__*/createReactComponent<JSX.VerdocsHelpIcon, HTMLVerdocsHelpIconElement>('verdocs-help-icon', undefined, undefined, defineVerdocsHelpIcon);
export const VerdocsInitialDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsInitialDialog, HTMLVerdocsInitialDialogElement>('verdocs-initial-dialog', undefined, undefined, defineVerdocsInitialDialog);
export const VerdocsKbaDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsKbaDialog, HTMLVerdocsKbaDialogElement>('verdocs-kba-dialog', undefined, undefined, defineVerdocsKbaDialog);
export const VerdocsLoader = /*@__PURE__*/createReactComponent<JSX.VerdocsLoader, HTMLVerdocsLoaderElement>('verdocs-loader', undefined, undefined, defineVerdocsLoader);
export const VerdocsOkDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsOkDialog, HTMLVerdocsOkDialogElement>('verdocs-ok-dialog', undefined, undefined, defineVerdocsOkDialog);
export const VerdocsOrganizationCard = /*@__PURE__*/createReactComponent<JSX.VerdocsOrganizationCard, HTMLVerdocsOrganizationCardElement>('verdocs-organization-card', undefined, undefined, defineVerdocsOrganizationCard);
export const VerdocsPagination = /*@__PURE__*/createReactComponent<JSX.VerdocsPagination, HTMLVerdocsPaginationElement>('verdocs-pagination', undefined, undefined, defineVerdocsPagination);
export const VerdocsPortal = /*@__PURE__*/createReactComponent<JSX.VerdocsPortal, HTMLVerdocsPortalElement>('verdocs-portal', undefined, undefined, defineVerdocsPortal);
export const VerdocsPreview = /*@__PURE__*/createReactComponent<JSX.VerdocsPreview, HTMLVerdocsPreviewElement>('verdocs-preview', undefined, undefined, defineVerdocsPreview);
export const VerdocsProgressBar = /*@__PURE__*/createReactComponent<JSX.VerdocsProgressBar, HTMLVerdocsProgressBarElement>('verdocs-progress-bar', undefined, undefined, defineVerdocsProgressBar);
export const VerdocsQuickFilter = /*@__PURE__*/createReactComponent<JSX.VerdocsQuickFilter, HTMLVerdocsQuickFilterElement>('verdocs-quick-filter', undefined, undefined, defineVerdocsQuickFilter);
export const VerdocsQuickFunctions = /*@__PURE__*/createReactComponent<JSX.VerdocsQuickFunctions, HTMLVerdocsQuickFunctionsElement>('verdocs-quick-functions', undefined, undefined, defineVerdocsQuickFunctions);
export const VerdocsRadioButton = /*@__PURE__*/createReactComponent<JSX.VerdocsRadioButton, HTMLVerdocsRadioButtonElement>('verdocs-radio-button', undefined, undefined, defineVerdocsRadioButton);
export const VerdocsSearch = /*@__PURE__*/createReactComponent<JSX.VerdocsSearch, HTMLVerdocsSearchElement>('verdocs-search', undefined, undefined, defineVerdocsSearch);
export const VerdocsSearchBox = /*@__PURE__*/createReactComponent<JSX.VerdocsSearchBox, HTMLVerdocsSearchBoxElement>('verdocs-search-box', undefined, undefined, defineVerdocsSearchBox);
export const VerdocsSearchTabs = /*@__PURE__*/createReactComponent<JSX.VerdocsSearchTabs, HTMLVerdocsSearchTabsElement>('verdocs-search-tabs', undefined, undefined, defineVerdocsSearchTabs);
export const VerdocsSelectInput = /*@__PURE__*/createReactComponent<JSX.VerdocsSelectInput, HTMLVerdocsSelectInputElement>('verdocs-select-input', undefined, undefined, defineVerdocsSelectInput);
export const VerdocsSend = /*@__PURE__*/createReactComponent<JSX.VerdocsSend, HTMLVerdocsSendElement>('verdocs-send', undefined, undefined, defineVerdocsSend);
export const VerdocsSign = /*@__PURE__*/createReactComponent<JSX.VerdocsSign, HTMLVerdocsSignElement>('verdocs-sign', undefined, undefined, defineVerdocsSign);
export const VerdocsSignatureDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsSignatureDialog, HTMLVerdocsSignatureDialogElement>('verdocs-signature-dialog', undefined, undefined, defineVerdocsSignatureDialog);
export const VerdocsSpinner = /*@__PURE__*/createReactComponent<JSX.VerdocsSpinner, HTMLVerdocsSpinnerElement>('verdocs-spinner', undefined, undefined, defineVerdocsSpinner);
export const VerdocsStatusIndicator = /*@__PURE__*/createReactComponent<JSX.VerdocsStatusIndicator, HTMLVerdocsStatusIndicatorElement>('verdocs-status-indicator', undefined, undefined, defineVerdocsStatusIndicator);
export const VerdocsTable = /*@__PURE__*/createReactComponent<JSX.VerdocsTable, HTMLVerdocsTableElement>('verdocs-table', undefined, undefined, defineVerdocsTable);
export const VerdocsTabs = /*@__PURE__*/createReactComponent<JSX.VerdocsTabs, HTMLVerdocsTabsElement>('verdocs-tabs', undefined, undefined, defineVerdocsTabs);
export const VerdocsTemplateAttachments = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateAttachments, HTMLVerdocsTemplateAttachmentsElement>('verdocs-template-attachments', undefined, undefined, defineVerdocsTemplateAttachments);
export const VerdocsTemplateBuildTabs = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateBuildTabs, HTMLVerdocsTemplateBuildTabsElement>('verdocs-template-build-tabs', undefined, undefined, defineVerdocsTemplateBuildTabs);
export const VerdocsTemplateCard = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateCard, HTMLVerdocsTemplateCardElement>('verdocs-template-card', undefined, undefined, defineVerdocsTemplateCard);
export const VerdocsTemplateCreate = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateCreate, HTMLVerdocsTemplateCreateElement>('verdocs-template-create', undefined, undefined, defineVerdocsTemplateCreate);
export const VerdocsTemplateDocumentPage = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateDocumentPage, HTMLVerdocsTemplateDocumentPageElement>('verdocs-template-document-page', undefined, undefined, defineVerdocsTemplateDocumentPage);
export const VerdocsTemplateFieldProperties = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateFieldProperties, HTMLVerdocsTemplateFieldPropertiesElement>('verdocs-template-field-properties', undefined, undefined, defineVerdocsTemplateFieldProperties);
export const VerdocsTemplateFields = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateFields, HTMLVerdocsTemplateFieldsElement>('verdocs-template-fields', undefined, undefined, defineVerdocsTemplateFields);
export const VerdocsTemplateName = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateName, HTMLVerdocsTemplateNameElement>('verdocs-template-name', undefined, undefined, defineVerdocsTemplateName);
export const VerdocsTemplateReminders = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateReminders, HTMLVerdocsTemplateRemindersElement>('verdocs-template-reminders', undefined, undefined, defineVerdocsTemplateReminders);
export const VerdocsTemplateRoleProperties = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateRoleProperties, HTMLVerdocsTemplateRolePropertiesElement>('verdocs-template-role-properties', undefined, undefined, defineVerdocsTemplateRoleProperties);
export const VerdocsTemplateRoles = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateRoles, HTMLVerdocsTemplateRolesElement>('verdocs-template-roles', undefined, undefined, defineVerdocsTemplateRoles);
export const VerdocsTemplateSender = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateSender, HTMLVerdocsTemplateSenderElement>('verdocs-template-sender', undefined, undefined, defineVerdocsTemplateSender);
export const VerdocsTemplateStar = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateStar, HTMLVerdocsTemplateStarElement>('verdocs-template-star', undefined, undefined, defineVerdocsTemplateStar);
export const VerdocsTemplateTags = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateTags, HTMLVerdocsTemplateTagsElement>('verdocs-template-tags', undefined, undefined, defineVerdocsTemplateTags);
export const VerdocsTemplateVisibility = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplateVisibility, HTMLVerdocsTemplateVisibilityElement>('verdocs-template-visibility', undefined, undefined, defineVerdocsTemplateVisibility);
export const VerdocsTemplatesList = /*@__PURE__*/createReactComponent<JSX.VerdocsTemplatesList, HTMLVerdocsTemplatesListElement>('verdocs-templates-list', undefined, undefined, defineVerdocsTemplatesList);
export const VerdocsTextInput = /*@__PURE__*/createReactComponent<JSX.VerdocsTextInput, HTMLVerdocsTextInputElement>('verdocs-text-input', undefined, undefined, defineVerdocsTextInput);
export const VerdocsToggle = /*@__PURE__*/createReactComponent<JSX.VerdocsToggle, HTMLVerdocsToggleElement>('verdocs-toggle', undefined, undefined, defineVerdocsToggle);
export const VerdocsToggleButton = /*@__PURE__*/createReactComponent<JSX.VerdocsToggleButton, HTMLVerdocsToggleButtonElement>('verdocs-toggle-button', undefined, undefined, defineVerdocsToggleButton);
export const VerdocsToolbarIcon = /*@__PURE__*/createReactComponent<JSX.VerdocsToolbarIcon, HTMLVerdocsToolbarIconElement>('verdocs-toolbar-icon', undefined, undefined, defineVerdocsToolbarIcon);
export const VerdocsUploadDialog = /*@__PURE__*/createReactComponent<JSX.VerdocsUploadDialog, HTMLVerdocsUploadDialogElement>('verdocs-upload-dialog', undefined, undefined, defineVerdocsUploadDialog);
export const VerdocsView = /*@__PURE__*/createReactComponent<JSX.VerdocsView, HTMLVerdocsViewElement>('verdocs-view', undefined, undefined, defineVerdocsView);
